info:
  name: search-engine
  version: 1.0.0

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    encoding: UTF-8
    schemas: public
    locations: classpath:migrations
    validate-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'env', 'metrics', 'auditevents', 'beans', 'caches', 'configprops', 'flyway', 'httptrace', 'mappings', 'scheduledtasks', 'threaddump', 'heapdump', 'logfile', 'prometheus', 'loggers']
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
